### ISSUE TITLE
State support for other JDKs

### ISSUE THREAD

**Issue by mppfiles** [javalite/javalite-site#19]
Currently the [release page](http://javalite.io/release-notes-23) (all of them) states that the only supported jdk is "Oracle JDK", which us propietary. What about OpenJDK for example?
This could stop new adopters...

**Comment by ipolevoy** [comment]
this has to do with Travis. We already have two builds, one supporting Java 8, the other supports Java11. 

The other problem is the Korlin support. It uses a Dokka Maven plugin to generate JavaDoc from Kotlin, but  the plugin  does not support OpeJDK!!! https://github.com/javalite/javalite/issues/962

Without  the JavaDoc jar, Sonatype rejects new releases. While the framework itself  perfectly supports JOracle JDK as well as OpenJDK, these unpleasant environment issues prevent us from running separate builds. 

This: https://github.com/Kotlin/dokka/issues/294 is still open. When they fix this issue, we will be able to add two more builds: OpenJDK + Java8 and OpenJDK + java11. 

Alternatively, we could drop Kotlin support for the time being, or hack some Java dummy class into it - either approach is a hack.

**Comment by mppfiles** [comment]
I understand! Anyway it's important to clearly state the difference: requirements for using the framework vs for building it! May I submit a PR?

**Comment by ipolevoy** [comment]
yes, of course! I have a feeling we will have to get away  from Travis and back to Jenkins. The problem with Travis, it is insanely slow. A build takes 5 - 6 times longer on Travis because it starts building VMs according to config before it ruins the build - and it does this for every database ActiveJDBC supports: https://travis-ci.org/javalite/javalite/builds. 

So, we should really have 4 builds to confidently state that we are supoporting all Oracle and Open JDK for Java 8 and 11+. This means migration to Jenkins because I cannot bear to wait for 4 hours for a single commit!
